name: Deploy Spring Boot App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-username: ${{ secrets.SSH_USERNAME }}
        ssh-host: ${{ secrets.SSH_HOST }}

    - name: Install OpenJDK
      run: sudo apt-get install openjdk-19-jre -y

    - name: Build Spring Boot Application
      run: ./mvnw package

    - name: SSH into DigitalOcean Server
      run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "systemctl stop cooking.service && cd /var/www/cooking-accademy-backend/ && mvn clean install -DskipTests && systemctl start cooking.service"
