name: Deploy Spring Boot App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install OpenJDK
      run: sudo apt-get install openjdk-19-jre -y

    - name: Set up SSH
      uses: appleboy/ssh-action@master
      with:
        ssh-private-key: "!n#xB#RE4BDmHapP"
        ssh-username: "root"
        ssh-host: 207.154.220.132

          script:|
            sudo cd /var/www/cooking-accademy-backend/
            git config pull.rebase true 
            git pull origin main  
            sudo /opt/apache-maven-3.9.4/bin/mvn clean install -DskipTests
            sudo systemctl stop cooking.service  
            sudo systemctl start cooking.service
