name: Deploy Spring Boot App to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install OpenJDK
      run: sudo apt-get install openjdk-19-jre -y

    - name: Set up SSH
      uses: appleboy/ssh-action@master
      with:
        ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}
        ssh-username: ${{secrets.SSH_USERNAME}}
        ssh-host: ${{secrets.SSH_HOST}}

          script:|
            sudo cd /var/www/cooking-accademy-backend/  
            sudo /opt/apache-maven-3.9.4/bin/mvn clean install -DskipTests
            sudo systemctl stop cooking.service  
            sudo systemctl start cooking.service
          
